### ISSUE TITLE
Ignore all chat from non players

### ISSUE THREAD

**Issue by smc87** [CraftIRC/3#56]
Hello, sorry if there is already a config option i did not find.

Is there anyway a feature could be added that allows you to ignore all chat from anyone whos IRC nick does not match a player name that has previously logged into the server?

This feature is in dynmap chat, but i much prefer craftIRC to that. 

Thanks in advance.

SMC

**Comment by smc87** [comment]
Hey...yes my fork has this feature. I'm not sure it would be an easy pull though..I have quite alot of custom stuff in my fork.

Feel free to pull anything back in that you like though.

**Comment by dequis** [comment]
Too late, this is closed because we did the final release of craftirc3 and don't plan to continue development on it anymore.

**Comment by mbax** [comment]
Hi @smc87 

Future development for CraftIRC has moved to [Sponge](http://spongepowered.org), since Bukkit development stopped in August 2014. 

CraftIRC4 is a total rewrite all the way down, including using a new IRC library, and is in fairly early stages. It's functional, but doesn't have all the fancy features CraftIRC3 has yet. :)
